language = "C"
pragma_once = true
include_version = true
cpp_compat = true
usize_is_size_t = true
style = "both"

include_guard = "BINETTE_H"

[export]
include = [
  "BinetteByteBuffer",
  "BinetteLocalAccessTag",
  "BinetteLocalBackendAbi",
  "BinetteLocalDescriptorAbi",
  "BinetteLocalDescriptorHandle",
  "BinetteLocalEnumAbi",
  "BinetteLocalEnumTagAccessAbi",
  "BinetteLocalEnumTagThunk",
  "BinetteLocalEnumTagThunkAbi",
  "BinetteLocalFieldAbi",
  "BinetteLocalKindAbi",
  "BinetteLocalKindTag",
  "BinetteLocalLayoutAbi",
  "BinetteLocalOptionAbi",
  "BinetteLocalOptionIsSomeThunk",
  "BinetteLocalOptionRepresentationAbi",
  "BinetteLocalOptionRepresentationTag",
  "BinetteLocalOptionSomeThunk",
  "BinetteLocalOptionThunksAbi",
  "BinetteLocalOptionWriteNoneThunk",
  "BinetteLocalOptionWriteSomeBytesThunk",
  "BinetteLocalScalarAbi",
  "BinetteLocalScalarTag",
  "BinetteLocalSchemaRefAbi",
  "BinetteLocalSchemaRefTag",
  "BinetteLocalSequenceAbi",
  "BinetteLocalSequenceElementPtrThunk",
  "BinetteLocalSequenceLenThunk",
  "BinetteLocalSequenceStorageAbi",
  "BinetteLocalSequenceStorageTag",
  "BinetteLocalSequenceThunksAbi",
  "BinetteLocalSequenceU8Thunk",
  "BinetteLocalSequenceWriteBytesThunk",
  "BinetteLocalSequenceWriteFixedElementsThunk",
  "BinetteLocalStrAbi",
  "BinetteLocalStructAbi",
  "BinetteLocalVariantAbi",
  "BinetteLocalVariantConstructAbi",
  "BinetteLocalVariantConstructThunk",
  "BinetteLocalVariantDropAbi",
  "BinetteLocalVariantDropProjectedThunk",
  "BinetteLocalVariantProjectAccessAbi",
  "BinetteLocalVariantProjectIntoAbi",
  "BinetteLocalVariantProjectIntoThunk",
  "BinetteLocalVariantProjectThunk",
  "BinetteLocalVariantProjectThunkAbi",
]
